version: '3.1'
services:
    db:
        image: mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: test_db
        ports:
            - "3307:3306"
        volumes:
            - .:/docker-entrypoint-initdb.d